### ISSUE TITLE
Hi, gaby

### ISSUE THREAD

**Issue by IndyNYU** [gabywang/FRE6883#1]
Hi, nice to meet u.
 You r also take part in the financial computing class? Tue or Sat? 
I am new to C++ and GitHub, and I appreciate communication : )

**Comment by gabywang** [comment]
Hi Indy,

Nice to meet you too. :)
I'm taking the Saturday class this semester. I don't have much c++ experience but I used to upload and save my projects/coding homework on Github. Feel free to chat with me. 😃
